version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URI: mongodb://root:password@mongo:27017/payeever?authSource=admin
      RABBITMQ_URI: amqp://rabbitmq
    depends_on:
      - mongo
      - rabbitmq

  mongo:
    image: mongo:6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - '27017:27017'

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672' # RabbitMQ service
      - '15672:15672' # RabbitMQ management UI
